### ISSUE TITLE
Obviously a very good tool ... but ...

### ISSUE THREAD

**Issue by asdf8dfafjk** [hantmac/tmax#21]
I hope you're aware that there already exists one by the name `just` that does something similar.

**Comment by hantmac** [comment]
> I hope you're aware that there already exists one by the name `just` that does something similar.

Would you like to share the project link of exists one which similar to `tmax`?

**Comment by asdf8dfafjk** [comment]
Sorry! 
https://github.com/casey/just

**Comment by hantmac** [comment]
> Sorry!
> https://github.com/casey/just

Thanks, but I think `just` is a little bit complicated to use though powerful, and it does not have interactive mode, search mode .

**Comment by asdf8dfafjk** [comment]
Please don't get me wrong, my intention was not to compare. I was hoping if I could help you with a preexisting tool since you were kind enough to open source yours.

**Comment by hantmac** [comment]
> Please don't get me wrong, my intention was not to compare. I was hoping if I could help you with a preexisting tool since you were kind enough to open source yours.

Got it, thanks very much.
